resources:

  - name: utility_scriptRepo
    type: GitRepo
    configuration:
      path: jpline/sample-script
      branches:
        include: master
      gitProvider: varsha_github
      
  - name: mvnBuild_infoTest
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_sample_build_varsha
      buildNumber: 9
   
  - name: r_Aql
    type: Aql
    configuration:
      sourceArtifactory: varsha_artifactory
      query: ""
#       addedProperties:
#         key1: value1
#         key2: value2
#       mappings:
#         - name: mapping1
#           input: testInput  
#           output: testInput
          
pipelines:
  - name: Varsha_pipeline
    steps: 
      - name: utility_u16
        type: Bash
        configuration:
          inputResources:
            - name: r_BuildInfo
            - name: r_Aql
#               - name: utility_scriptRepo
#               - name: imagePrivate
#           inputSteps:
#               - name: utility_u18test
#           integrations:
#               - name: varsha_slack
#           outputResources:
#               - name: webhookInt
          environmentVariables:
            ENV1: value1
            ENV2: value2
        execution:
          onExecute:
            - printenv
