resources:

  - name: utility_scriptRepo
    type: GitRepo
    configuration:
      path: jpline/sample-script
      branches:
        include: master
      gitProvider: varsha_github
      
  - name: mvnBuild_infoTest
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_sample_build_varsha
      buildNumber: 9
      
pipelines:
  - name: Varsha_pipeline
    steps: 
      - name: utility_u16
        type: Bash
        configuration:
#           timeoutSeconds: 360
#           affinityGroup: u16grp
#           nodePool: ubuntu16
          inputResources:
            - name: mvnBuild_infoTest
#               - name: utility_scriptRepo
#               - name: imagePrivate
#           inputSteps:
#               - name: utility_u18test
#           integrations:
#               - name: varsha_slack
#               - name: varshaJira
#               - name: varsha_internalWebhook
#           outputResources:
#               - name: webhookInt
#               - name: utility_testRepo
          environmentVariables:
            ENV1: value1
            ENV2: value2
        execution:
          onExecute:
            - printenv
