resources:
  - name: mvnBuild_info
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_example_build
      buildNumber: 1
      
  - name: mvn_repo
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/project-examples
 
pipelines:
  - name: varshamvn
    steps:
      - name: mvnBuild_sample
        type: MvnBuild
        configuration:
          nodePool: varsha_u16
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: mvn_repo
          integrations:
            - name: varsha_artifactory
            - name: varsha_slack
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
        execution:
          onStart:
           # - apt install default-jdk
#             - pushd /tmp
#             - wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
#             - tar xzvf apache-maven-3.6.1-bin.tar.gz
#             - export PATH=$PATH:/tmp/apache-maven-3.6.1/bin
#             - export M2_HOME=/tmp/apache-maven-3.6.1/
#             - popd
            - javac -version
            - mvn --version
          onSuccess:
            - send_notifications varsha_slack
            
      - name: mvnBuild_publish
        type: PublishBuildInfo
        configuration:
          nodePool: varsha_u16
          integrations:
            - name: varsha_artifactory
          inputSteps:
            - name: mvnBuild_sample
          outputResources:
            - name: mvnBuild_info
