pipelines:

  - name: pipelines_test
    steps:
      - name: S_Bash_test
        type: Bash
        configuration:
          nodePool: azure_test
        execution:
          onExecute:
            - echo "executing step..."
            - printenv
