pipelines:
  - name: pipe_helloWorld
    steps:
      - name: sampleBash
        type: Bash
        configuration:
          nodePool: build_c7
        execution:
          onExecute:
            - echo "Hello world"
