pipelines:
  - name: varsha_genericIntegration
    steps: 
      - name: genericIntegration_jsonToString
        type: Bash
        configuration:
          integrations:
            - name: generic_json_string
        execution:
          onExecute:
            - printenv
            - export "key=$int_generic_json_string_test"
            - echo "$key"
