pipelines:

  - name: pipelines_test
    steps:
      - name: S_Bash_test
        type: Bash
        configuration:
          nodePool: c7-us-west-dynamic
        execution:
          onExecute:
            - echo "executing step..."
            - printenv
