pipelines:

  - name: pipelines_test
    steps:
#       - name: S_Bash_test
#         type: Bash
#         configuration:
#           nodePool: azure-2384
#         execution:
#           onExecute:
#             - echo "executing step..."
#             - printenv


      - name: win_test
        type: PowerShell
        configuration:
          nodePool: azure-2384
        execution:
          onExecute:
            - Get-Variable | format-table
            - docker ps -a
