resources:

  - name: S_Bash_0508_FileSpec_test
    type: FileSpec
    configuration:
      sourceArtifactory: varsha_art
      pattern: "example-repo-local/setup/test.sh"
      recursive: false

  - name: S_Bash_0510_Image_test
    type: Image
    configuration:
      registry: varsha_docker
      imageName: shipbeta00/ubuntu
      imageTag: master
      autoPull: true
      
pipelines:

  - name: pipelines_S_Bash_0508_test
    steps:
      - name: S_Bash_0508_test
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0508_FileSpec_test
        execution:
          onExecute:
            - echo "executing step..."
            
      - name: S_Bash_0510_test
        type: Bash
        configuration:
          inputSteps:
            - name: S_Bash_0508_test
          inputResources:
            - name: S_Bash_0510_Image_test
        execution:
          onExecute:
            - echo "executing step..."
