jobs:
  - name: simplerunsh
    type: runSh
    steps:
      - IN: repo
      - TASK:
        - script: ls
       # - script: cat big.txt >> bigger_file.txt
        #- script: cat big.txt >> bigger_file.txt
       # - script: cat bigger_file.txt
        #- script: sleep 3m
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
      - NOTIFY: notify-slack
