language: 
  - node_js

# Version number
node_js: 
  - 4.2.1

build:
  ci: 
    - node --version
    - jfrog rt dl test-jfrog-ship/testoct.sh
    
integrations:                               
  hub:
    - integrationName: jatin-jfrog
      type: artifactoryKey    

resources:
  - name: jatin-newrelic
    type: notification
    integration: jatin-newrelic

  - name: jatin-slack
    type: notification
    integration: jatin-slack
    
  - name: jatin-samplerepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: jatindogra/sample-repo
      branch: master
      
jobs:
  - name: use_custom_image-u16
    type: runSh
    runtime:                 
      nodePool: u16
    steps:
      - IN: jatin-newrelic    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: newrelic
          script:
            - shipctl get_integration_resource jatin-newrelic
            - shipctl notify jatin-newrelic --type='deployment' --appId=248443265 --revision='ReViSiOn' --user='jatinsrelic'

  - name: use_custom_image-u14
    type: runSh
    runtime:                 
      nodePool: u14
    steps:
      - IN: jatin-newrelic    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: newrelic
          script:
            - shipctl notify jatin-newrelic --type='deployment' --appId=248443265 --revision='ReViSiOn' --user='jatinsrelic'

  - name: use_custom_image-centos
    type: runSh
    runtime:                 
      nodePool: centos
    steps:
      - IN: jatin-newrelic    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: newrelic
          script:
            - shipctl notify jatin-newrelic --type='deployment' --appId=248443265 --revision='ReViSiOn' --user='jatinsrelic'

  - name: use_custom_image-aarch64
    type: runSh
    runtime:                 
      nodePool: default-restricted
    steps:
      - IN: jatin-newrelic    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: newrelic
          script:
            - shipctl get_integration_resource jatin-newrelic
            - shipctl notify jatin-newrelic --type='deployment' --appName=jatin-newrelic --revision='ReViSiOn' --user='jatinsrelic'

  - name: use_custom_image-aarch32
    type: runSh
    runtime:                 
      nodePool: shippable-shared-aarch32
    steps:
      - IN: jatin-newrelic    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: newrelic
          script:
            - shipctl notify jatin-newrelic --type='deployment' --appName=jatin-newrelic --revision='ReViSiOn' --user='jatinsrelic'

  - name: use_custom_image-windows
    type: runSh
    runtime:                 
      nodePool: windows
    steps:
      - IN: jatin-slack    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: slack
          script:
            - shipctl notify jatin-slack -recipient "@shiptest-rc-ow"
 
  - name: use_custom_image-win714
    type: runSh
    runtime:                 
      nodePool: win
    steps:
      - IN: jatin-slack    # Configuring this as IN automatically logs you into your Docker registry
      - IN: jatin-samplerepo
      - TASK:
          name: slack
          script:
            - shipctl notify jatin-slack -recipient "@shiptest-rc-ow"
