jobs:
  - name: pull-manifest1
    type: manifest
    steps:
      - IN: pull-image1
        pull: false
      - IN: pull-image2
        pull: true
      - IN: pull-dopts1
      - IN: pull-params1
        applyTo:
          - pull-image1
      - TASK: managed
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
     
  - name: pull-manifest2
    type: manifest
    steps:
      - IN: pull-image2
        pull: true
      - IN: pull-tpdopts1
      - TASK: managed
      
  - name: pull-manifest3
    type: manifest
    steps:
      - IN: pull-image2
        pull: false
      - TASK: managed
      
  - name: pull-manifest4
    type: manifest
    steps:
      - IN: pull-image2
      - IN: pull-tpdopts1
      - TASK: managed
      
  #- name: sp-tpdeploy1
   # type: tripubDeploy
    #steps:
     # - IN: sp-manifest1
      #- IN: sp-manifest2
      #- IN: tripub-cluster
      #- TASK: managed
       # deployMethod: upgrade
  
  - name: pull-runsh1
    type: runSh
    steps:
      - IN: pull-samegitrepo
      - IN: pull-image1
        pull: true
      - IN: pull-file1
        pull: false
      - TASK:
        - script: ls
  
  - name: pull-runsh2image
    type: runSh
    steps:
      - IN: pull-samegitrepo
      - IN: pull-image1
        pull: true
      - IN: pull-image2
        pull: false
      - IN: pull-image3
      - TASK:
        - script: ls
  
  - name: pull-runs3file
    type: runSh
    steps:
      - IN: pull-samegitrepo
      - IN: pull-file1
        pull: true
      - IN: pull-file2
        pull: false
      - IN: pull-file3
      - TASK:
        - script: ls
        
  - name: pulltrue-runsh
    type: runSh
    steps:
      - IN: pull-samegitrepo
      - IN: pull-image1
        pull: true
      - IN: pull-file1
        pull: true
      - TASK:
        - script: ls
  
  - name: pullfalse-runsh
    type: runSh
    steps:
      - IN: pull-samegitrepo
      - IN: pull-image1
        pull: false
      - IN: pull-file1
        pull: false
      - TASK:
        - script: ls
   
  - name: withoutpull-runsh
    type: runSh
    steps:
      - IN: pull-samegitrepo
      - IN: pull-image1
      - IN: pull-file1
      - TASK:
        - script: ls
        
