triggers:
   - name: clitrigger1
     type: trigger
     version:
       counter: 0
       
   - name: clitrigger2
     type: trigger
     version:
       counter: 0
       
   - name: clitrigger3
     type: trigger
     version:
       counter: 0
