# Language setting
language: python

# Version number
python:
  - "2.7"
  - "pypy3"
  
env:
  global:
    - TEST1=pvtenv
    - secure: BPadRRYqA9yyfugIB6wRE9QMJn+aojYMDemPAgA4qhdo1jKduEiI/P58NhDquZ36HnjCuRnZdZ8z0PsGyeO0MT2UCqjtOxVRm1fnt2tfHEPSBvpQVRymXlXC3lbJcdDuknahx+r3vTuV21Gha2XWbQaM6cOHDuW4C++6IYh87YCwtbG66n6Hhs/QBQRyn1zGGK8HST5mVEiqq/Jn1v4OUTmMMqnk8FE2OAQYnf7gDS1TWFyhuij/CC6sL8rZw0HKvYBzpeEZo+QL9aI3YoxfO09jpFsF2vkQzkgO3inCjI1NU6M/+NN3Vwcs1NLqw5eM7fdKXBav/ORME7k543tSDA==
    ########### TEST2=pvtenvSecure
    
  matrix:
    - TEST3=pvtenv3
    - secure: udOvjFIFXqTQB8RSsZdS6p1Gl+EHGI8uyIs9FO5a9HZrc/4uxNNgxQUJH3t+3xUwlK9N2QNxwKDM/ZmGdqowtUqcFQgtl8omplFmdHDZOcuYp9k6pxN+Wtix+bMyNPR/ZzWpgZVJdOsRldERScgG1HvfWhHW0k4QyLjCil9v8A24bhoVIYFsfiUlpg4jMNLtqm0GLaiz09X9fzM/Cvt3aL/cySItddKGGybLPz8UfnUU3OWUhAnriyVoTXC3tRwfuzRaLTDguJ4NR+i92DQHZdiiNIwis9w4qWVK4Q0MsJ2GVQ0EcGjXG0aCWAfWtINWSvb794MOdXLa/cNsR4TD0Q==
    ########### TEST4=pvtenvSecureMatrix
    
build:
  ci:
    - python --version
    - echo "TEST1=$TEST1"
    - echo "TEST2=$TEST2"
    - echo "TEST3=$TEST3"
    - echo "TEST4=$TEST4"

resources:

#CLICONFIG
  - name: ar-dockercli
    type: cliConfig
    integration: "docker"
    
  - name: ar-awscli
    type: cliConfig
    integration: "awskeys"

  - name: ar-gclcli
    type: cliConfig
    integration: "gcl"
    
#CLUSTERS
  - name: ar-ddccluster
    type: cluster
    integration: ddc
    pointer:
      sourceName : "nothing" #we can anything because it is mandatory but ddc doesnot have clusters

  - name: ar-awscluster
    type: cluster
    integration: awskeys
    versionTemplate: 
      region: us-east-1
      sourceName: clu1
      
#DOCKER OPTIONS
  - name: ar-dockeroptions
    type: dockerOptions
    version:
      memory: 100

#FILES
  - name: ar-files
    type: file
    integration: docker
    pointer:
      sourceName: "random"
    seed:
      versionName: "random-2"

#GITREPO:
  - name: ar-gitrepo
    type: gitRepo
    integration: "github"
    pointer:
      sourceName: "Varsha-Arun/sample-script"
      branch: master
      #tags:
       # only:
        #  - v1.*
      buildOnCommit: true    
      buildOnPullRequest: true
      buildOnRelease: true
      buildOnTagPush: true
      
#IMAGES
  - name: ar-image
    type: image
    integration: docker
    pointer:
      sourceName: "shippabledocker/pipelinev2"
    seed:
      versionName: "deploy.1"
  
  - name: ar-loadBalancerImage
    type: image
    integration: gcl
    pointer:
      sourceName: asia.gcr.io/lithe-camp-182705/nginx #public image which is running 
      isPull: true
    seed:
      versionName: "latest"

#INTEGRATION
  - name: ar-dockerintegration
    type: integration
    integration: "docker"

#LOAD BALANCER      
  - name: ar-gke-service-lb
    type: loadBalancer 
    integration: gcl
    pointer:
      sourceName: "servicetestlb"  # the service name (metadata.name) this source name 
      method: ClusterIP # the service type Kubernetes default: ClusterIP
      clusterName: "testnode2" # The namespace for the service - cluster name
      region: "asia-east1-a" #region of cluster n stuffs
      namespace: "default"    # optional
    version:
      ports:
        - name: lbports # Required for multiple ports, must be a DNS_LABEL
          protocol: TCP  # Kubernetes default: TCP
          port: 8001     # Required.
          targetPort: 8002 # A number in 1-65535 or an "IANA_SVC_NAME"  This is the port to access the pod.
         # nodePort: <integer> # Port exposed on the node.  Kubernetes will auto-allocate by default.
      selector:
        new: lb
        
#  - name: ar-loadbalancer
 #   type: loadBalancer
 #   pointer:
 #     sourceName: EC2Contai-EcsElast-GPCOXIIKWPUJSREYA

#NOTIFICATIONS
  - name: ar-slack
    type: notification
    integration: "slack"
    pointer:
      recipients:
        - "#rc-private"
        - "#rc-public"
        - "@shiptest-rc-ow"
        - "#random"
   
  - name: ar-hipchat
    type: notification
    integration: "notify-hipchat"
    pointer:
      recipients:
        - "#rc-private"
        - "#rc-public"
        - "@shiptest.rc.ow"        
        - "#random"
   
  - name: ar-irc
    type: notification
    #integration: "irc"
    versionTemplate:
      method: irc
      recipients:
        - "#rc-test"
   
  - name: ar-email
    type: notification
    #integration: "email"
    versionTemplate:
      method: email
      recipients:
        - "varsha@shippable.com"

#PARAMS
  - name: ar-params
    type: params
    version:
      params:
        foo: bar
        TEST1: env1        
        secure: BPadRRYqA9yyfugIB6wRE9QMJn+aojYMDemPAgA4qhdo1jKduEiI/P58NhDquZ36HnjCuRnZdZ8z0PsGyeO0MT2UCqjtOxVRm1fnt2tfHEPSBvpQVRymXlXC3lbJcdDuknahx+r3vTuV21Gha2XWbQaM6cOHDuW4C++6IYh87YCwtbG66n6Hhs/QBQRyn1zGGK8HST5mVEiqq/Jn1v4OUTmMMqnk8FE2OAQYnf7gDS1TWFyhuij/CC6sL8rZw0HKvYBzpeEZo+QL9aI3YoxfO09jpFsF2vkQzkgO3inCjI1NU6M/+NN3Vwcs1NLqw5eM7fdKXBav/ORME7k543tSDA==
        ######### TEST2=pvtenvSecure
        TEST3: env3
        DB_HOST: "ds015700.mlab.com"
        DB_NAME: "ayeaye"
        DB_PORT: "15700"
        DB_USERNAME: "aye0aye"
        DB_PASSWORD: "aye0aye"
        ENVIRONMENT: "test-aws"
      
        
#REPLICAS
  - name: ar-replica
    type: replicas
    version:
      count: 2

#STATE
  - name: ar-state
    type: state
    
#TIME
  - name: ar-testtime
    type: time
    seed:
      interval: "1 1 1 * *" #"*/9 * 9 9 *"
      
#VERSIONS

  - name: ar-version
    type: version
    seed:
      versionName: "6.1.2"

jobs:

#DEPLOY  
  - name: ar-awsdeploy
    type: deploy
    allowPublicAccess: true
    steps:
      - IN: ar-awscluster
      - IN: ar-manifest
        #switch: off
      - IN: ar-params
      - IN: ar-dockeroptions
      - IN: ar-replica
        #versionNumber: 1000 
        
#JENKINSJOB
 # - name: ar-jenkins                  # a memorable, unique name. this is how your job will be referred to in shippable pipelines
 #   type: jenkinsJob                  # The type of the job (should not be changed by the user)
 #   integration: "jenkins"       # The name of your Jenkins integration (created via accountSettings page)
 #   pointer:
 #     sourceName: "firstjob1"         # The name of your Jenkins job
 #   steps:
 #     - OUT: "ar-files" 

#MANIFESTS
  - name: ar-manifest
    type: manifest
    steps:
      - IN: ar-image
      # versionNumber: 100
      #- OUT: ar-image4invalidformat
      - IN: ar-tg1
    allowPublicAccess: true

#PROVISION
      
#  - name: ar-provisionlb
 #   type: provision
 #   steps:
  #    - IN: ar-loadBalancerImage
  
  - name: ar-deployServicelb
    type: provision
    steps:
      - IN: ar-gke-service-lb
      
#RELEASE
  - name: ar-release
    type: release
    allowPublicAccess: true
    on_start:
      - NOTIFY: ar-slack
    steps:
      - IN: ar-version
         #versionName: testrelease
      - IN: ar-inrunSh
      - TASK: managed
        bump: rc
       #- IN: ar-tg3
    flags:
      - ar-release    
    on_success:
      - NOTIFY: ar-slack
      - NOTIFY: ar-hipchat
      - NOTIFY: ar-irc
      - NOTIFY: ar-email
    on_failure:
      - NOTIFY: ar-slack
      - NOTIFY: ar-hipchat
      - NOTIFY: ar-irc
      - NOTIFY: ar-email

#RUNCI
  - name: sample_pipelines_runCI
    type: runCI
    #allowPublicAccess: true
    on_start:
     - NOTIFY: ar-slack
    steps:
      - IN: ar-dockercli
         #versionName: testrelease
    flags:
      - sample_pipelines_runCI
      
#RUNSH      
  - name: ar-inrunSh
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: ar-params
      - IN: ar-gitrepo
        showBuildStatus: true
      # versionName: testsha
      - TASK:
          runtime:
            options:
              imageName: "drydock/u16all" #"drydock/aarch64_u16all"
              imageTag: master
          script: 
            - ls
            - ./IN/ar-gitrepo/gitRepo/echo.sh
            - export FOO=foo1
            - echo $FOO
            - echo "TEST1=$TEST1"
            - echo "TEST2=$TEST2"
            - echo "TEST3=$TEST3"
            - lsb_release -a
            - docker --version
            - docker info
            - docker ps 
     # - OUT: ar-image2invalidimg    
    on_success:
      - script: echo 'Success'
    on_failure:
      - script: echo 'Failure runSh'
      - NOTIFY: ar-slack

#RUNCLI      
  - name: ar-inrunshPublicJob
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: ar-gitrepo
      # versionName: testsha
      - IN: ar-dockercli
      - IN: ar-testtime
      #- IN: ar-loadbalancer
      - IN: ar-files
      - TASK:
        - script: ls
        - script: ./IN/ar-gitrepo/gitRepo/echo.sh        
      
  - name: runshlongconsole
    type: runSh
    steps:
      - IN: ar-gitrepo
      # versionName: testsha
      - IN: ar-dockercli
      - IN: ar-testtime
      #- IN: ar-loadbalancer
      - IN: ar-files
      - TASK:
        - script: ls
        - script: ./IN/ar-gitrepo/gitRepo/echo.sh
        
triggers:

#TRIGGER
  - name: ar-tg1
    type: trigger
    version:
      counter: 1   
