pipelines:
  - name: varshabash12
    steps:
      - name: testReport_u1612
        type: Bash
        configuration:
          runtime:            
            type: image #host
              image:
#               auto:
#                 language: java
#                 versions:
#                   - openjdk8
                custom:
                  name: shippabledocker/sample_node_pvt
                  tag: masterpyt
        execution:
          onExecute:
            - printenv

      - name: test
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u1612
          runtime:            
            type: host #image
#             image:
#               auto:
#                 language: java
#                 versions:
#                   - openjdk8
#               custom:
#                 name: drydock/u16java
#                 tag: master
        execution:
          onExecute:
            - printenv
