# Language setting
language: python

# Version number
python:
  - "pypy3"
  
build:
  ci:
    - wget https://norvig.com/big.txt
    - cat big.txt # >> bigger_file.txt
    #- cat big.txt >> bigger_file.txt
   # - cat bigger_file.txt

jobs:
  - name: largeconsolerunsh
    type: runSh
    steps:
      #- IN: repo
      - TASK:
        - script: ls
        - script: wget https://norvig.com/big.txt
        - script: cat big.txt #>> bigger_file.txt
        #- script: cat big.txt >> bigger_file.txt
        #- script: cat bigger_file.txt
        #- script: ./GET/infra-repo/infra-repo/provision.sh
    always:
      - script: echo "This works on_always"
  
