pipelines:
  - name: varshabash12
    steps:
      - name: testReport_u1612
        type: Bash
        configuration:
          integrations:
            - name: varsha_docker
          runtime:            
            type: image #host
            image:
#               auto:
#                 language: java
#                 versions:
#                   - openjdk8
              custom:
                name: shippabledocker/pipelinev2 #shippabledocker/sample_node_pvt
                tag: deploy.1
        execution:
          onExecute:
            - printenv


      - name: test
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u1612
          runtime:            
            type: host #image
#             image:
#               auto:
#                 language: java
#                 versions:
#                   - openjdk8
#               custom:
#                 name: drydock/u16java
#                 tag: master
        execution:
          onExecute:
            - printenv
