resources:
  - name: custom_image_repo
    type: GitRepo
    configuration:
      path: Varsha-Arun/sample-script
      gitProvider: varsha_github 
      
pipelines:
  - name: custom_image_pipelines
    steps:
      - name: push_custom_image
        type: Bash
        configuration:
          integrations:
            - name: varsha_docker
          inputResources:
            - name: custom_image_repo
        execution:
          onExecute:
            - cd $res_custom_image_repo_resourcePath
            - sudo docker build -t shippabledocker/jfreq:run_id .
            - sudo docker push shippabledocker/jfreq:$run_id
#           # - write_output custom_image_repo "imageTag=$run_id"

      - name: using_custom_image
        type: Bash
        configuration:
          integrations:
            - name: varsha_art
          inputSteps:
            - name: push_custom_image
          runtime:            
            type: image #host
            image:
#               auto:
#                 language: java
#                 versions:
#                   - openjdk8
              custom:
                name: shippabledocker/jfreq
                tag: $run_id
        execution:
          onExecute:
            - touch foo
            - jfrog rt u foo test-generic-local/foo
            - echo hello > sample.txt
            - jfrog rt u sample.txt example-repo-local/setup/sample.txt
