resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: Varsha-Arun/sample-script
    configuration:
      integrationName: github
      branches:
        only: master
      tags:
        except: none
        only: none   
      buildOnCommit: true
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnRelease: true
      buildOnTagPush: true
      buildOnFileCommit: "*test"
      shallowDepth: 2
      gitConfig: 
        - dont_know
        - dont_know_2
    initialVersion:
      sha: master
      
  - name: nodeImg
    type: image
    imageName: shippabledocker/sample_node
    configuration:
      integrationName: dockerInt
    initialVersion:
      imageTag: latest
  
pipelines:
  - name: pipeline_1
    steps:    
      - name: testjob1
        type: bash
        configuration:
          priority: 3
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - echo "hello"
            - sleep 2m
            
      - name: testjob2
        type: bash
       # configuration:
        #  priority: 3
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - testjob1
        execution:
          onExecute:
            - echo "step2"
            
      - name: testjob3
        type: bash
        configuration:
          priority: 2
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - testjob1
        execution:
          onExecute:
            - echo "step3"
            - sleep 3m
            
      - name: testjob4
        type: bash
        configuration:
          priority: 1
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          steps:
            - nodeImg
        execution:
          onExecute:
            - echo "step4"   
            - sleep 3m

  - name: pipeline_2
    steps:    
      - name: buildTest
        type: bash
        configuration:
          priority: 11
        setup:
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16all
               tag: master
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - echo "hello"
            - sleep 2m
            
     # - name: test2
     #   type: bash
     #   setup:
     #     runtime:
     #       type: image
     #       image:
     #        custom:
     #          name: drydock/u16all
    #           tag: master
    #    triggeredBy:
    #      steps:
    #        - testjob1
    #    execution:
    #      onExecute:
    #        - echo "test2"

    #  - name: push-test3
    #    type: bash
    #    setup:
    #      runtime:
    #        type: image
    #        image:
    #         custom:
   #            name: drydock/u16all
   #            tag: master
   #     requires:
   #       integrations:
   #         - artifactorytest
   #     triggeredBy:
   #       steps:
  #          - test2
  #      execution:
  #        onExecute:
  #          - echo "push-Test3"

 #     - name: job2
 #       type: bash
#        setup:
#          runtime:
 #           type: image
 #           image:
 #            custom:
 #              name: drydock/u16all
 #              tag: master
 #       triggeredBy:
 #         steps:
 #           - testjob1
 #       execution:
 #         onExecute:
 #           - echo "job2"
