resources:

  - name: utility_scriptRepo
    type: GitRepo
    configuration:
      path: Varsha-Arun/sample-script
      branches:
        include: master
      gitProvider: varsha_github

 # - name: utility_bb
  #  type: GitRepo
  #  configuration:
  #    path: shiptest-rc-me/jfrog-pipelines
  #    branches:
  #      include: master
  #    gitProvider: varsha_bb
      
  - name: utility_gl
    type: GitRepo
    configuration:
      path: varsha-arun/jfrog_pipelines
      branches:
        include: master
      gitProvider: varsha_gl
      
pipelines:

  - name: varsha_simpleBash1
    steps:   
      - name: u18BashStep1
        type: Bash
        configuration:
          nodePool: ubuntu16_node
          integrations:
            - name: varsha_aws
          inputResources:
            - name: utility_scriptRepo
            - name: utility_gl
        #  outputResources:
        #    - name: webhookIntExternal
        execution:
          onExecute:
            - printenv
 
      - name: u18BashStep2
        type: Bash
        configuration:
          nodePool: ubuntu16_node
          timeoutSeconds: 360
          integrations:
            - name: varsha_aws
          inputSteps:
            - name: u18BashStep1
          inputResources:
            - name: utility_scriptRepo
        #  outputResources:
        #    - name: webhookIntExternal
        execution:
          onExecute:
            - printenv
