resources:

  - name: A_RunResourceVersions_Imagetest
    type: Image
    configuration:
      registry: varsha_docker
      imageName: shippabledocker/sample_node_pvt
      imageTag: master

  - name: sample_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: varsha_art
      pattern: example-repo-local/setup/sample.txt
      
  - name: utility_scriptRepo
    type: GitRepo
    configuration:
      path: Varsha-Arun/sample-script
      branches:
        include: master
      gitProvider: varsha_github

 # - name: utility_bb
  #  type: GitRepo
  #  configuration:
  #    path: shiptest-rc-me/jfrog-pipelines
  #    branches:
  #      include: master
  #    gitProvider: varsha_bb
      
#   - name: utility_gl
#     type: GitRepo
#     configuration:
#       path: varsha-arun/jfrog_pipelines
#       branches:
#         include: master
#       gitProvider: varsha_github
      
pipelines:

  - name: varsha_simpleBash1
    steps:   
      - name: u18BashStep1
        type: Bash
        configuration:
# #           nodePool: ubuntu16_node
          integrations:
            - name: varsha_art
#           inputResources:
#             - name: utility_scriptRepo
#             - name: utility_gl
          outputResources:
            - name: A_RunResourceVersions_Imagetest
        execution:
          onExecute:
            - touch foo
            - echo hello > sample.txt
           # - jfrog rt u foo test-generic-local/foo
            - jfrog rt u sample.txt example-repo-local/setup/sample.txt
            #- jfrog rt del example-repo-local/foo
#             - pushd $res_utility_scriptRepo_resourcePath
#             - ./echo.sh
#             - popd
            - printenv
            - write_output A_RunResourceVersions_Imagetest "imageTag=$masterpyt"
 
#       - name: u18BashStep2
#         type: Bash
#         configuration:
# #           nodePool: ubuntu16_node
# #           timeoutSeconds: 360
# #           integrations:
# #             - name: varsha_aws
#           inputSteps:
#             - name: u18BashStep1
#           inputResources:
#             - name: utility_scriptRepo
#         #  outputResources:
#         #    - name: webhookIntExternal
#         execution:
#           onExecute:
#             - printenv



  - name: varsha_test
    steps:   
      - name: test
        type: Bash
        configuration:
          inputResources:
            #- name: A_RunResourceVersions_Imagetest
            - name: sample_FileSpec
        execution:
          onExecute:
#             - pushd $res_utility_scriptRepo_resourcePath
#             - ./echo.sh
#             - popd
            - printenv
