resources:
  - name: test_sample_repo
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/sample_pipelines
      branches:
        include: master
      
pipelines:
  - name: step_testReports
    steps:
      - name: testReporttest
        type: Bash
        configuration:
          inputResources:
            - name: test_sample_repo
        execution:
          onExecute:
            - cd $res_test_sample_repo_resourcePath
            - ls
            - python -m py_compile calc.py
            - pip install --upgrade pip
            - hash -d pip
            - pip install pytest            
            - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
            - save_tests $res_test_sample_repo_resourcePath/test-reports/results.xml 
