# Language setting
language: python

# Version number
python:
  - 2.7

build:
  ci:
    - python --version

resources:

#CLICONFIG
  - name: iar-dockercli
    type: cliConfig
    integration: "docker"

#CLUSTERS
  - name: iar-ddccluster
    type: cluster
    integration: ddc
    pointer:
      sourceName : "nothing" #we can anything because it is mandatory but ddc doesnot have clusters

#DOCKER OPTIONS
  - name: iar-dockeroptions
    type: dockerOptions
    version:
      memory: 100
      
  - name: iar-dockeroptions2
    type: dockerOptions
    version:
      memoryReservations: 64
      
#FILES
  - name: iar-files
    type: file
    integration: docker
    pointer:
      sourceName: "random"
    seed:
      versionName: "random-2"

#GITREPO:
  - name: iar-gitrepo
    type: gitRepo
    integration: "github"
    pointer:
      sourceName: "Varsha-Arun/sample_pipelines"
      branch: master
      #tags:
       # only:
        #  - v1.*
      buildOnCommit: true    
      buildOnPullRequest: true
      buildOnRelease: true
      buildOnTagPush: true
      
#IMAGES
  - name: iar-image
    type: image
    integration: docker
    pointer:
      sourceName: "shippabledocker/pipelinev2"
    seed:
      versionName: "deploy.1"

#INTEGRATION
  - name: iar-dockerintegration
    type: integration
    integration: "docker"

#LOAD BALANCER
  - name: iar-loadbalancer
    type: loadBalancer
    pointer:
      sourceName: EC2Contai-EcsElast-GPCOXIIKWPUJSREYA

#NOTIFICATIONS
  - name: iar-slack
    type: notification
    integration: "slack"
    pointer:
      recipients:
        - "#pipeline-pvt"
        - "#pipeline-public"
        - "@shiphitchcock1"
        - "#random"

#PARAMS
  - name: iar-params
    type: params
    version:
      params:
        foo: bar
        secure: vrzA7eiJMV5mOlo1Sx5NWH5PDKIDrjCcfI3eY0XY5jqO1BU7K83z/JG8Ar6dBABpQ4raKMRX6+K0QvZFJ176yl7mvU01vBsuDG9JmpljNyBrf0uW+I6WFI5vPcf+ajrWxNBEIRRqQ2n0wPauT6aLMMAcJ1os05QqyewuTEuN4+RaNT3uBqv8nwN2FwUcit1PtbABrdYNZyEx0rQv/3PbnruFOggat1QzCPnEJx/lm1f0xKrsm3EgwGXcoLKKrM7u3SHV/erqvpSpGTdgphs0RmKOrtQ6I1Y+JgaK1gylu+esAxAwhQGirzwkV4QEo8OpzTiG5l1rzTcae427Lig28A==
        DB_HOST: "ds015700.mlab.com"
        DB_NAME: "ayeaye"
        DB_PORT: "15700"
        DB_USERNAME: "aye0aye"
        DB_PASSWORD: "aye0aye"
        ENVIRONMENT: "test-aws"
       
#REPLICAS
  - name: iar-replica
    type: replicas
    version:
      count: 2

#STATE
  - name: iar-state
    type: state
    
#TIME
  - name: iar-testtime
    type: time
    seed:
      interval: "1 1 1 * *" #"*/9 * 9 9 *"
      
#VERSIONS

  - name: iar-version
    type: version
    seed:
      versionName: "5.11.1"

jobs:

#DEPLOY  
  - name: iar-ddcdeploy
    type: deploy
    allowPublicAccess: true
    steps:
      - IN: iar-ddccluster
      - IN: iar-manifest
        switch: off
      - IN: iar-params
      - IN: iar-dockeroptions
      - IN: iar-replica
        #versionNumber: 1000 
        
#JENKINSJOB
#  - name: iar-jenkins                 # a memorable, unique name. this is how your job will be referred to in shippable pipelines
 #   type: jenkinsJob                  # The type of the job (should not be changed by the user)
 #   integration: "jenkins"            # The name of your Jenkins integration (created via accountSettings page)
  #  pointer:
 #     sourceName: "firstjob1"         # The name of your Jenkins job
  #  steps:
  #    - OUT: "iar-files" 

#MANIFESTS
  - name: iar-manifest
    type: manifest
    steps:
      - IN: iar-image
      # versionNumber: 100
      #- OUT: iar-image4invalidformat
      - IN: iar-tg1
    allowPublicAccess: true

#PROVISION
  - name: iar-provision                                              #required
    type: provision                                                  #required
    steps:
      - IN: iar-files 
      
#RELEASE
  - name: iar-release
    type: release
    #allowPublicAccess: true
    on_start:
      - NOTIFY: iar-slack
    steps:
      - IN: iar-version
         #versionName: testrelease
      - IN: iar-inrunSh
      - TASK: managed
        bump: rc
    flags:
      - iar-release    
    on_success:
      - NOTIFY: iar-slack
    on_failure:
      - NOTIFY: iar-slack

#RUNCI
  - name: sample_pipelines_runCI
    type: runCI
    #allowPublicAccess: true
    steps:
      - IN: iar-dockercli
         #versionName: testrelease

#RUNSH      
  - name: iar-inrunSh
    type: runSh
    allowPublicAccess: true
    on_start:
      - NOTIFY: iar-slack
      - script: echo 'on start'
    steps:
      - IN: iar-gitrepo
      # versionName: testsha
      - TASK:
        - script: ls
        - script: ./IN/iar-gitrepo/gitRepo/echo.sh
        - script: export FOO=foo1
        - script: echo $FOO
     # - OUT: iar-image2invalidimg    
    on_success:
      - script: echo 'Success'
    on_failure:
      - script: echo 'Failure runSh'
      - NOTIFY: iar-slack

#RUNCLI      
 # - name: iar-inrunCLI
 #   type: runCLI
 #   allowPublicAccess: true
  #  steps:
  #    - IN: iar-gitrepo
  #    # versionName: testsha
  #    - IN: iar-dockercli
  #    - IN: iar-testtime
  #    - IN: iar-loadbalancer
  #    - IN: iar-files
  #    - TASK:
  #      - script: ls
  #      - script: ./IN/iar-gitrepo/gitRepo/echo.sh

triggers:

#TRIGGER
  - name: iar-tg1
    type: trigger
    version:
      counter: 0
